import RubyImage from '../../photos/ruby.jpg'
import JavaScriptImage from '../../photos/javascript.jpg'
import PythonImage from '../../photos/python.jpg'
import PHPImage from '../../photos/php.png'
import JavaImage from '../../photos/java.jpg'
import CSharpImage from '../../photos/c_sharp.png'
import CPlusPlusImage from '../../photos/cplusplus.jpg'
import CObjectiveImage from '../../photos/cobjective.jpg'
import PerlImage from '../../photos/perl.jpg'
import ManagmentImage from '../../photos/managment.jpg'
import UserAvatar from '../../photos/user_avatar.jpg'

const courses = [
  {
    "id": 0,
    "label": "Ruby",
    "mark": 6,
    "author": {
      "login": "Akira",
      "avatar": UserAvatar,
    },
    "whyContent": "Ruby is a general-purpose language that is still popular and in high demand in the marketplace, as it’s more commonly used in Rails applications. Concise and readable, it is easy to pick up but also plenty powerful. Companies like Twitter, Soundcloud, Goodreads, and Kickstarter got their products off the ground with Ruby.",
    "willContent": "In this course, you will gain familiarity with Ruby and basic programming concepts—including variables, loops, control flow, and most importantly, object-oriented programming. You’ll get a chance to test your understanding in a final project, which you’ll build locally.",
    "image": RubyImage,
    "usesCount": 198,
    "successRate": 87,
    "course_tags": [
      {
        "tag": {
          id: 0,
          name: "IT",
        }
      }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
   },
  {
    "id": 1,
    "label": "JavaScript",
    "mark": 8,
    "author": {
      "login": "Kioshi",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": JavaScriptImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
   },
  {
    "id": 2,
    "label": "Python",
    "mark": 7,
    "author": {
      "login": "Aurumlie",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": PythonImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }, { id: 2, name: "AI"}],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
   },
  {
    "id": 3,
    "label": "PHP",
    "mark": 5,
    "author": {
      "login": "Magny",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": PHPImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
  },
  {
    "id": 4,
    "label": "Java",
    "mark": 6,
    "author": {
      "login": "Gaara",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": JavaImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
  },
  {
    "id": 5,
    "label": "C#",
    "mark": 6,
    "author": {
      "login": "Shikamary",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": CSharpImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
   },
  {
    "id": 6,
    "label": "C++",
    "mark": 4,
    "author": {
      "login": "Hikari",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": CPlusPlusImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
  },
  {
    "id": 7,
    "label": "C Objective",
    "mark": 3,
    "author": {
      "login": "Ikar",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": CObjectiveImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
  },
  {
    "id": 8,
    "label": "Perl",
    "mark": 2,
    "author": {
      "login": "Itachi",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": PerlImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{id: 0, name: "IT"}, {id: 1, name: "programming languages" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
   },
  {
    "id": 9,
    "label": "Managment",
    "mark": -2,
    "author": {
      "login": "Kira",
      "avatar": UserAvatar,
    },
    "whyContent": "",
    "willContent": "",
    "image": ManagmentImage,
    "usesCount": 10,
    "successRate": 87,
    "tags": [{ id: 10, name: "communications" }, { id: 11, name:"people" }, { id: 12, name: "society" }, { id: 13, name: "business" }],
    "accessType": 'public',
    "status": 'ready',
    "members": [],
    "organization": null,
    "certificateTemplate": '',
  }
]

export default courses;