require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
    Enabled: false

Metrics/MethodLength:
  Max: 1000

Metrics/BlockLength:
  Exclude:
    - config/**/*

Metrics/ClassLength:
  Exclude:
    - app/services/**/*