require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
    Enabled: false

Metrics/MethodLength:
  Max: 1000

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - app/services/**/*

Rails/FilePath:
  Exclude:
    - config/**/*

Layout/LineLength:
  Exclude:
    - config/**/*

Style/BlockComments:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*

Style/IfUnlessModifier:
  Exclude:
    - config/**/*

Layout/ArgumentAlignment:
  Exclude:
    - config/**/*