export const GET_COURSE = "GET_COURSE";
export const CREATE_COURSE = "CREATE_COURSE";
export const GET_COURSES = "GET_COURSES";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const SET_DRAFT_COURSE = "SET_DRAFT_COURSE";
export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const UPDATE_COURSE_APPROVE_STATUS = "UPDATE_COURSE_APPROVE_STATUS";
export const DROP_COURSE = "DROP_COURSE";

export const GET_MY_COURSES = "GET_MY_COURSES";
export const GET_RECOMMENDED_COURSES = "GET_RECOMMENDED_COURSES";
