export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const SET_CURRENT_ORGANIZATION = "SET_CURRENT_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
