export const GET_UNREGISTERED_MEMBERS = 'GET_UNREGISTERED_MEMBERS'
export const CREATE_UNREGISTERED_MEMBER = 'CREATE_UNREGISTERED_MEMBER'
export const DROP_UNREGISTERED_MEMBER = 'DROP_UNREGISTERED_MEMBER'