export const GET_USER_COURSES = 'GET_USER_COURSES'
export const ADD_USER_COURSE = 'ADD_USER_COURSE'
export const UPDATE_USER_COURSE = 'UPDATE_USER_COURSE'

export const GET_DONE_COURSES = 'GET_DONE_COURSES'
export const GET_CURRENT_COURSES = 'GET_CURRENT_COURSES'
export const GET_FAVORITE_COURSES = 'GET_FAVORITE_COURSES'